CREATE TYPE "ApplicationStage" AS ENUM ('SAVED', 'APPLIED', 'RECRUITER_SCREENING', 'ASSESSMENT', 'TECHNICAL_INTERVIEW', 'MANAGERIAL_INTERVIEW', 'FINAL_INTERVIEW', 'OFFER', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'NO_RESPONSE');
CREATE TYPE "WorkMode" AS ENUM ('REMOTE', 'HYBRID', 'ONSITE', 'UNSPECIFIED');
CREATE TYPE "EmploymentType" AS ENUM ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', 'UNSPECIFIED');
CREATE TYPE "Priority" AS ENUM ('LOW', 'MEDIUM', 'HIGH');
CREATE TYPE "TimelineEventType" AS ENUM ('CREATED', 'STAGE_CHANGED', 'RECRUITER_CONTACTED', 'FOLLOW_UP_SENT', 'INTERVIEW_SCHEDULED', 'INTERVIEW_COMPLETED', 'NOTE_ADDED', 'REJECTION_RECEIVED', 'OFFER_RECEIVED', 'CUSTOM');

CREATE TABLE "User" ("id" TEXT PRIMARY KEY, "name" TEXT, "email" TEXT NOT NULL UNIQUE, "emailVerified" TIMESTAMP(3), "image" TEXT, "passwordHash" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Account" ("userId" TEXT NOT NULL, "type" TEXT NOT NULL, "provider" TEXT NOT NULL, "providerAccountId" TEXT NOT NULL, "refresh_token" TEXT, "access_token" TEXT, "expires_at" INTEGER, "token_type" TEXT, "scope" TEXT, "id_token" TEXT, "session_state" TEXT, PRIMARY KEY ("provider", "providerAccountId"));
CREATE TABLE "Session" ("sessionToken" TEXT NOT NULL UNIQUE, "userId" TEXT NOT NULL, "expires" TIMESTAMP(3) NOT NULL);
CREATE TABLE "VerificationToken" ("identifier" TEXT NOT NULL, "token" TEXT NOT NULL, "expires" TIMESTAMP(3) NOT NULL, PRIMARY KEY ("identifier", "token"));
CREATE TABLE "Application" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL, "companyName" TEXT NOT NULL, "roleTitle" TEXT NOT NULL, "location" TEXT, "workMode" "WorkMode" NOT NULL DEFAULT 'UNSPECIFIED', "employmentType" "EmploymentType" NOT NULL DEFAULT 'UNSPECIFIED', "sourcePlatform" TEXT, "sourceUrl" TEXT, "appliedAt" TIMESTAMP(3), "stage" "ApplicationStage" NOT NULL DEFAULT 'SAVED', "salaryMin" INTEGER, "salaryMax" INTEGER, "currency" TEXT NOT NULL DEFAULT 'USD', "jobDescription" TEXT, "importantKeywords" TEXT[] NOT NULL, "priority" "Priority" NOT NULL DEFAULT 'MEDIUM', "notes" TEXT, "nextAction" TEXT, "rejectionReason" TEXT, "learningNote" TEXT, "archivedAt" TIMESTAMP(3), "recruiterContactId" TEXT, "resumeVersionId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "ApplicationTimelineEvent" ("id" TEXT PRIMARY KEY, "applicationId" TEXT NOT NULL, "type" "TimelineEventType" NOT NULL, "title" TEXT NOT NULL, "description" TEXT, "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "RecruiterContact" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL, "name" TEXT NOT NULL, "company" TEXT, "role" TEXT, "email" TEXT, "phone" TEXT, "linkedInUrl" TEXT, "notes" TEXT, "lastContactAt" TIMESTAMP(3), "nextFollowUpAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "FollowUp" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL, "applicationId" TEXT, "recruiterContactId" TEXT, "title" TEXT NOT NULL, "notes" TEXT, "dueAt" TIMESTAMP(3) NOT NULL, "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Interview" ("id" TEXT PRIMARY KEY, "applicationId" TEXT NOT NULL, "type" TEXT NOT NULL, "roundName" TEXT NOT NULL, "scheduledAt" TIMESTAMP(3) NOT NULL, "timezone" TEXT NOT NULL, "interviewerName" TEXT, "meetingUrl" TEXT, "location" TEXT, "preparationNotes" TEXT, "questionsAsked" TEXT, "reflections" TEXT, "result" TEXT, "followUpAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "ResumeVersion" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL, "name" TEXT NOT NULL, "targetRole" TEXT, "description" TEXT, "keywords" TEXT[] NOT NULL, "externalUrl" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Note" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL, "title" TEXT, "content" TEXT NOT NULL, "applicationId" TEXT, "recruiterContactId" TEXT, "interviewId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Tag" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL, "name" TEXT NOT NULL);
CREATE TABLE "ApplicationTag" ("applicationId" TEXT NOT NULL, "tagId" TEXT NOT NULL, PRIMARY KEY ("applicationId", "tagId"));
CREATE TABLE "UserSettings" ("userId" TEXT PRIMARY KEY, "timezone" TEXT NOT NULL DEFAULT 'UTC', "preferredCurrency" TEXT NOT NULL DEFAULT 'USD', "noResponseThresholdDays" INTEGER NOT NULL DEFAULT 14, "weeklyApplicationGoal" INTEGER NOT NULL DEFAULT 5, "appearance" TEXT NOT NULL DEFAULT 'system');

CREATE UNIQUE INDEX "Tag_userId_name_key" ON "Tag"("userId", "name");
CREATE INDEX "Application_userId_stage_idx" ON "Application"("userId", "stage");
CREATE INDEX "Application_userId_appliedAt_idx" ON "Application"("userId", "appliedAt");
CREATE INDEX "Application_userId_companyName_idx" ON "Application"("userId", "companyName");
CREATE INDEX "ApplicationTimelineEvent_applicationId_occurredAt_idx" ON "ApplicationTimelineEvent"("applicationId", "occurredAt");
CREATE INDEX "RecruiterContact_userId_name_idx" ON "RecruiterContact"("userId", "name");
CREATE INDEX "FollowUp_userId_dueAt_idx" ON "FollowUp"("userId", "dueAt");
CREATE INDEX "FollowUp_userId_completedAt_idx" ON "FollowUp"("userId", "completedAt");
CREATE INDEX "Interview_applicationId_scheduledAt_idx" ON "Interview"("applicationId", "scheduledAt");
CREATE INDEX "ResumeVersion_userId_isActive_idx" ON "ResumeVersion"("userId", "isActive");
CREATE INDEX "Note_userId_updatedAt_idx" ON "Note"("userId", "updatedAt");

ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Application" ADD CONSTRAINT "Application_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Application" ADD CONSTRAINT "Application_recruiterContactId_fkey" FOREIGN KEY ("recruiterContactId") REFERENCES "RecruiterContact"("id") ON DELETE SET NULL;
ALTER TABLE "Application" ADD CONSTRAINT "Application_resumeVersionId_fkey" FOREIGN KEY ("resumeVersionId") REFERENCES "ResumeVersion"("id") ON DELETE SET NULL;
ALTER TABLE "ApplicationTimelineEvent" ADD CONSTRAINT "ApplicationTimelineEvent_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE;
ALTER TABLE "RecruiterContact" ADD CONSTRAINT "RecruiterContact_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "FollowUp" ADD CONSTRAINT "FollowUp_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "FollowUp" ADD CONSTRAINT "FollowUp_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE;
ALTER TABLE "FollowUp" ADD CONSTRAINT "FollowUp_recruiterContactId_fkey" FOREIGN KEY ("recruiterContactId") REFERENCES "RecruiterContact"("id") ON DELETE SET NULL;
ALTER TABLE "Interview" ADD CONSTRAINT "Interview_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE;
ALTER TABLE "ResumeVersion" ADD CONSTRAINT "ResumeVersion_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Note" ADD CONSTRAINT "Note_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Note" ADD CONSTRAINT "Note_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE;
ALTER TABLE "Note" ADD CONSTRAINT "Note_recruiterContactId_fkey" FOREIGN KEY ("recruiterContactId") REFERENCES "RecruiterContact"("id") ON DELETE CASCADE;
ALTER TABLE "Note" ADD CONSTRAINT "Note_interviewId_fkey" FOREIGN KEY ("interviewId") REFERENCES "Interview"("id") ON DELETE CASCADE;
ALTER TABLE "Tag" ADD CONSTRAINT "Tag_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "ApplicationTag" ADD CONSTRAINT "ApplicationTag_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE;
ALTER TABLE "ApplicationTag" ADD CONSTRAINT "ApplicationTag_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "Tag"("id") ON DELETE CASCADE;
ALTER TABLE "UserSettings" ADD CONSTRAINT "UserSettings_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
